language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
before_install:
  - pip install git+https://github.com/pepkit/ubiquerg.git@dev
  - pip install git+https://github.com/pepkit/peppy.git@dev
  - pip install git+https://github.com/pepkit/divvy.git@adapters
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-test.txt
script: pytest tests/smoketests --cov=looper
branches:
  only:
    - dev
    - master
