language: python
python:
  - "2.7"
os:
  - linux
  - osx
before_install:
  - pip install -U pip
install:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt
  - pip install -U -r requirements-test.txt
script: pytest
branches:
  only:
  - dev
  - master
