language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install -r requirements-test.txt
script: pytest
branches:
  only:
    - dev
    - master
